name: build & test contract
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Compile contracts
      run: truffle compile
    - name: Test contracts
      run: truffle test
